case $- in
    *i*) ;;
    *) return;;
esac

export HISTCONTROL=erasedups
export HISTSIZE=-1

shopt -s autocd
shopt -s histappend

bind -m vi '/: "\C-r"'

source "$(fzf-share)"/key-bindings.bash
source "$(fzf-share)"/completion.bash
