export HISTCONTROL=erasedups
export HISTSIZE=-1

shopt -s autocd
shopt -s histappend

bind -m vi '/: "\C-r"'

source "$(fzf-share)"/key-bindings.bash

get() {
    local pkgs pkg
    for pkg in "$@"; do
        if [[ $pkg == *#* ]]; then
            pkgs+=" $pkg"
        else
            pkgs+=" nixpkgs-local#$pkg"
        fi
    done
    NIXPKGS_ALLOW_UNFREE=1 nix shell$pkgs --impure
}

dev() {
    local workdir="$PWD"
    while [[ ! -f flake.nix ]] && [[ $PWD != / ]]; do
        cd ..
    done
    if [[ -f flake.nix ]]; then
        local flakedir="$PWD"
        mkdir -p .nix
        echo '*' > .nix/.gitignore
        [[ -f .nix/pin ]] || nix flake update
        cd $workdir
        nix develop --profile "$flakedir"/.nix/profile
    else
        echo nope
        cd $workdir
    fi
}
