export HISTCONTROL=erasedups
export HISTSIZE=-1

shopt -s autocd
shopt -s histappend

bind -m vi '/: "\C-r"'

source "$(fzf-share)"/key-bindings.bash

get() {
    pkgs=""
    for pkg in "$@"; do
        if [[ $pkg == *#* ]]; then
            pkgs+=" $pkg"
        else
            pkgs+=" shellpkgs#$pkg"
        fi
    done
    nix shell$pkgs
}

dev() {
    mkdir -p .nix
    echo '*' > .nix/.gitignore
    [[ -f .nix/pin ]] || nix flake update
    nix develop --profile .nix/profile
}
